### ISSUE TITLE
Final Capstone project: set up Kanban board

### ISSUE THREAD

**Issue by ShadyShawkat** [ShadyShawkat/Final-Capstone-rails-backend#19]
Hello 👋🏻,

We are a team of 5 and here is the complete list of team members that are working on this project:

1. Shady Shawkat: @ShadyShawkat 
2. Luis Abarca: @TheLuisAbarca 
3. Omar Muhamad: @Omar-Muhamad 
4. Mihreteab Misganaw: @Mre55 
5. Santiago Velosa: @vechicin 

You can view the kanban board for the front-end from [here](https://github.com/Omar-Muhamad/Final-Capstone-React-Frontend/projects/2).

![chrome-capture-2022-4-5](https://user-images.githubusercontent.com/68796232/167025616-61c21684-dd54-4fb3-9ce7-29d56b6c44f2.gif)

You can view the kanban board for the back-end from [here](https://github.com/ShadyShawkat/Final-Capstone-rails-backend/projects/1).

![back-end GIF](https://user-images.githubusercontent.com/62290545/167025817-3d4b56d8-ed99-4b5e-82b4-4aaf79f0f571.gif)

[Note] We completed one group task in the back-end kanban board, which was to create an ERD and you can view it from [here](https://github.com/ShadyShawkat/Final-Capstone-rails-backend/issues/1).

**Comment by MuriloRoque** [comment]
Hi @ShadyShawkat, @Mre55, @TheLuisAbarca, @Omar-Muhamad, @vechicin,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [x] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @ShadyShawkat, @Mre55, @TheLuisAbarca, @Omar-Muhamad, @vechicin,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
